services:
  postgres:
    image: postgres:16
    container_name: zomatox_pg
    environment:
      POSTGRES_DB: zomatox
      POSTGRES_USER: zomatox
      POSTGRES_PASSWORD: zomatox
    ports:
      - "5433:5432"
    volumes:
      - zomatox_pg_data:/var/lib/postgresql/data

volumes:
  zomatox_pg_data:
