spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blinkit
    username: blinkit
    password: blinkit
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
